# Generated by Django 4.1.1 on 2023-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
