# Generated by Django 4.1.1 on 2023-08-10 23:28

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=common.models.img_url, verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype_ID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
